name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: ./.github/actions/setup

      - name: Format code
        run: bun run format

      - name: Lint code
        run: bun run lint

      - name: Build
        run: bun run build
